set_property MARK_DEBUG true [get_nets zynq_bd_i/xadc_wiz_0_M_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[7]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[11]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[13]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/scope_trigger_0_out_data_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/scope_trigger_0_out_data_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/scope_trigger_0_out_data_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/scope_trigger_0_out_data_TDATA[13]}]
set_property MARK_DEBUG true [get_nets zynq_bd_i/xadc_wiz_0_M_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[14]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[15]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/scope_trigger_0_out_data_TDATA[7]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/scope_trigger_0_out_data_TDATA[10]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/scope_trigger_0_out_data_TDATA[11]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/scope_trigger_0_out_data_TDATA[15]}]
set_property MARK_DEBUG true [get_nets zynq_bd_i/scope_trigger_0_out_data_TLAST]
set_property MARK_DEBUG true [get_nets zynq_bd_i/scope_trigger_0_out_data_TREADY]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[8]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[9]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/xadc_wiz_0_M_AXIS_TID[0]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/xadc_wiz_0_M_AXIS_TID[1]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/scope_trigger_0_out_data_TDATA[12]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/xadc_wiz_0_M_AXIS_TID[3]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/scope_trigger_0_out_data_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/scope_trigger_0_out_data_TDATA[9]}]
set_property MARK_DEBUG true [get_nets zynq_bd_i/scope_trigger_0_out_data_TVALID]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[10]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[12]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/scope_trigger_0_out_data_TDATA[14]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/xadc_wiz_0_M_AXIS_TID[2]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/scope_trigger_0_out_data_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/scope_trigger_0_out_data_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/scope_trigger_0_out_data_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {zynq_bd_i/scope_trigger_0_out_data_TDATA[8]}]
set_property MARK_DEBUG true [get_nets zynq_bd_i/axi_dma_0_s2mm_introut]
set_property MARK_DEBUG true [get_nets zynq_bd_i/xadc_wiz_0/eos_out]
set_property MARK_DEBUG true [get_nets zynq_bd_i/xadc_wiz_0/eoc_out]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 4 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list zynq_bd_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {zynq_bd_i/scope_trigger_0_out_data_TDATA[0]} {zynq_bd_i/scope_trigger_0_out_data_TDATA[1]} {zynq_bd_i/scope_trigger_0_out_data_TDATA[2]} {zynq_bd_i/scope_trigger_0_out_data_TDATA[3]} {zynq_bd_i/scope_trigger_0_out_data_TDATA[4]} {zynq_bd_i/scope_trigger_0_out_data_TDATA[5]} {zynq_bd_i/scope_trigger_0_out_data_TDATA[6]} {zynq_bd_i/scope_trigger_0_out_data_TDATA[7]} {zynq_bd_i/scope_trigger_0_out_data_TDATA[8]} {zynq_bd_i/scope_trigger_0_out_data_TDATA[9]} {zynq_bd_i/scope_trigger_0_out_data_TDATA[10]} {zynq_bd_i/scope_trigger_0_out_data_TDATA[11]} {zynq_bd_i/scope_trigger_0_out_data_TDATA[12]} {zynq_bd_i/scope_trigger_0_out_data_TDATA[13]} {zynq_bd_i/scope_trigger_0_out_data_TDATA[14]} {zynq_bd_i/scope_trigger_0_out_data_TDATA[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[0]} {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[1]} {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[2]} {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[3]} {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[4]} {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[5]} {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[6]} {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[7]} {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[8]} {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[9]} {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[10]} {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[11]} {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[12]} {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[13]} {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[14]} {zynq_bd_i/xadc_wiz_0_M_AXIS_TDATA[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 4 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {zynq_bd_i/xadc_wiz_0_M_AXIS_TID[0]} {zynq_bd_i/xadc_wiz_0_M_AXIS_TID[1]} {zynq_bd_i/xadc_wiz_0_M_AXIS_TID[2]} {zynq_bd_i/xadc_wiz_0_M_AXIS_TID[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list zynq_bd_i/axi_dma_0_s2mm_introut]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list zynq_bd_i/xadc_wiz_0/eoc_out]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list zynq_bd_i/xadc_wiz_0/eos_out]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list zynq_bd_i/scope_trigger_0_out_data_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list zynq_bd_i/scope_trigger_0_out_data_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list zynq_bd_i/scope_trigger_0_out_data_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list zynq_bd_i/xadc_wiz_0_M_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list zynq_bd_i/xadc_wiz_0_M_AXIS_TVALID]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
